---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hypr-tail
# description will be included in the image's metadata
description: Bluefin-dx with Hyprland.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 42  # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /  # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: dnf
    repos:
      copr: [atim/starship]
    install:
      packages:
        # Original packages
        - micro
        - starship

        # Hyprland core
        - hyprland
        - waybar
        - rofi
        - dunst
        - grim
        - slurp
        - wl-clipboard
        - swayidle
        - foot

        # Desktop portals (essential for Wayland)
        - xdg-desktop-portal
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-wlr

        # System utilities that work better at system level
        - polkit-kde
        - pavucontrol
        - brightnessctl
        - playerctl
        - udisks2
        - ntfs-3g

        # File management
        - thunar
        - tumbler
        - caja
        - nautilus

        # Essential utilities
        - fastfetch
        - htop
        - bat
        - fd-find
        - ripgrep
        - fuzzel
        - fzf
        - tree
        - git
        - rsync
        - unzip
        - zip
        - tar

        # Text editors
        - helix
        - neovim

        # Development tools
        - git-lfs
        - nodejs
        - nodejs-npm

        # Multimedia basics
        - ffmpeg-free
        - mpv
        - ImageMagick

        # System monitoring
        - lsof
        - sysstat
        - smartmontools
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks  # also remove firefox dependency (not required for all packages, this is a special case)
  - type: default-flatpaks
    configurations:
      - notify: true  # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install:
          # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - app.zen_browser.zen
          - com.github.tchx84.Flatseal
          - io.gitlab.librewolf-community
          - net.nokyan.Resources
          - org.gnome.Papers
          - org.gnome.Decibels
          - org.gnome.font-viewer
          - org.localsend.localsend_app
          - org.gnome.Loupe
          - org.kde.filelight
          - com.github.marktext.marktext
      - scope: user  # Also add Flathub user repo, but no user packages
  # - type: fonts
  #   fonts:
  #     nerd-fonts: [FiraCode, JetBrainsMono, NerdFontsSymbolsOnly, CaskaydiaCove, GeistMono, IosevkaTerm, ZedMono]
  #     google-fonts: [Inter, Libre Baskerville, Lora, Noto Color Emoji, Noto Sans, Roboto, Space Mono]
  - type: signing  # this sets up the proper policy & signing files for signed images to work fully
